### ISSUE TITLE
Search issues when trying to add users to a collection

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons-team#26]
When trying to add users to a collection, a very limited number of users shows up in the search box.
<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a902e98c093955f48d5ffbe67ead084000c08d9/Screenshot%202024-07-23%20at%201.23.37%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 1.23.37 PM.png" />

Typing a user's full email address seems to work (although it doesn't preview until after the full address has been edited), but it doesn't appear until after the full address has been entered. <img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34fed1031488a1a256b4a0d023f0296512000186/Screenshot%202024-07-23%20at%201.30.19%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 1.30.19 PM.png" />

<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzhCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35c708e38c2b4576ef480cb28174dba05dcb05d9/Screenshot%202024-07-23%20at%201.30.32%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 1.30.32 PM.png" />

**Comment by monotasker** [comment]
- bool-prefix queries return as expected once default query type set back to "bool_prefix"
    - re-raises issues with result ordering in language, etc.
- users can't be found unless active is true
    - are users being activated via saml login?

**Comment by monotasker** [comment]
- added code to ensure SAML user accounts are activated on login
- implemented a "best_fields" search with a wildcard at the end of the string as a workable compromise
